### ISSUE TITLE
Choice of chapter in groups not allowed

### ISSUE THREAD

**Issue by russkibass** [dbinetti/barberscore-ember#19]
Tried to correct the wrong entry data in Groups- Garden City Chorus chapter. Augusta GA is wrong,  North Augusta SC is correct. Direct entry didn't work. Choosing the chapter by pressing spyglass returne 403 Forbidden error message.

**Comment by dbinetti** [comment]
In this case you needed to update the Chapter, which I've locked down.  I made the change.
