### ISSUE TITLE
Twitter window - need more characters

### ISSUE THREAD

**Issue by russkibass** [dbinetti/barberscore-ember#29]
Need more characters @LateShiftQuarte no room for the last "t" in Late shift, although wait, 15 characters is the current Twitter limit. @lateshiftquartet was not the twitter handle as I didn't find them

**Comment by dbinetti** [comment]
this validator is for the current twitter limit.  so their handle is wrong.  closing this ticket.

**Comment by russkibass** [comment]
Twitter handle is 15 characters. What is confusing FB uses Twitter looking handle for their messenger that starts with @. I thought it was Twitter n that's why it didn't work

-- 
Alexander Boltenko 
"Russki" Bass, St. Petersburg, FL
russkibass@barbershopharmony.org
@RusskibassTampa
singing bass with the Heralds of Harmony
Cell 269-501-SING (7464)
http://barberscore.com - best International contests tracker & database
"Barbershop quartet singing is four guys tasting the holy essence of four individual mechanisms coming into complete agreement."  (Meredith Willson)
